//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answers
    {
        public int AnswerId { get; set; }
        public string Answer { get; set; }
        public int UserId { get; set; }
        public System.DateTime AnsweredTimeDate { get; set; }
        public int QuestionId { get; set; }
        public Nullable<int> Comments { get; set; }
        public Nullable<double> Rating { get; set; }
    }
}
