//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using ForumDisscussion.Areas.ForumUser.Models;

namespace ForumDisscussion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForumTbConnectionDbContext : DbContext
    {
        public ForumTbConnectionDbContext()
            : base("name=ForumTbConnectionDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AnswerFlexibility> AnswerFlexibilities { get; set; }
        public DbSet<Answer> Answers { get; set; }
        public DbSet<Category> Categories { get; set; }
        public DbSet<ForumUser> ForumUsers { get; set; }
        public DbSet<Question> Questions { get; set; }
        //public DbSet<Temp> Comments { get; set; }
        public DbSet<Comment> Comments { get; set; }
    }
}
