//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ForumDataBaseConnectionContext : DbContext
    {
        public ForumDataBaseConnectionContext()
            : base("name=ForumDataBaseConnectionContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Answers> Answers { get; set; }
        public DbSet<Category> Category { get; set; }
        public DbSet<Comment> Comment { get; set; }
        public DbSet<ForumUser> ForumUser { get; set; }
        public DbSet<PostInformation> PostInformation { get; set; }
        public DbSet<Questions> Questions { get; set; }
        public DbSet<Rating> Rating { get; set; }
        public DbSet<Temp> Temp { get; set; }
    }
}
