//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PostInformation
    {
        public int PostId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> TotalQuesPost { get; set; }
        public Nullable<int> TotalAnsPost { get; set; }
        public Nullable<int> TotalCommentPost { get; set; }
        public Nullable<int> TotalValidPost { get; set; }
    }
}
