//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questions
    {
        public int QuestionId { get; set; }
        public string Question { get; set; }
        public int CategoryId { get; set; }
        public int UserId { get; set; }
        public System.DateTime PostedDate { get; set; }
        public int answers { get; set; }
        public int views { get; set; }
    }
}
