//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRatingTable
    {
        public int Id { get; set; }
        public double PreviousTotRating { get; set; }
        public int PresentRating { get; set; }
        public int PrevTotRater { get; set; }
    }
}
