//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ForumDisscussion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPostedQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public Nullable<int> UserId { get; set; }
        public string AnsUserId { get; set; }
        public string Answer { get; set; }
        public string ReplyUser { get; set; }
        public Nullable<System.DateTime> PostedDate { get; set; }
        public byte[] Image { get; set; }
        public Nullable<System.DateTime> QuesPostDate { get; set; }
        public string Category { get; set; }
        public Nullable<int> QuestionId { get; set; }
        public Nullable<int> TotalReplies { get; set; }
        public Nullable<int> TotalAnswer { get; set; }
    }
}
